apiVersion: batch/v1
kind: Job
metadata:
  name: cron
spec:
  template:
    metadata:
      name: cron
    spec:
      containers:
      - name: cron
        image: gcr.io/hots-cockroach/website:latest
        command: ["/website", "-cron", "-cockroach=postgres://root@cockroachdb-public:26257/?sslmode=disable"]
      restartPolicy: OnFailure
