apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  template:
    metadata:
      labels:
        app: website
        tier: web
    spec:
      containers:
      - name: website
        image: gcr.io/hots-cockroach/website:latest
        env:
          - name: EXEC
            value: "/cockroach start --background --insecure --store=/mnt/cockroach --max-sql-memory 50% --cache 50%"
          - name: AUTOCERT
            value: "hots.mattjibson.com"
        ports:
        - containerPort: 443
        - containerPort: 8080
        volumeMounts:
        - name: cockroach-storage
          mountPath: /mnt/cockroach
      volumes:
        - name: cockroach-storage
          gcePersistentDisk:
            pdName: hots-disk
            fsType: ext4
