apiVersion: batch/v1
kind: Job
metadata:
  name: elo
spec:
  template:
    metadata:
      name: elo
    spec:
      containers:
      - name: elo
        image: gcr.io/hots-cockroach/website:latest
        command: ["/website", "-elo", "-cockroach=postgres://root@cockroachdb-public:26257/?sslmode=disable"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: "5G"
      restartPolicy: Never
