apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elo
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: elo
            image: gcr.io/hots-cockroach/website:latest
            command: ["/website", "-elo", "2.30.3", "-cockroach=postgres://root@cockroachdb-public:26257/?sslmode=disable"]
            imagePullPolicy: Always
