apiVersion: batch/v1
kind: Job
metadata:
  name: import
spec:
  template:
    metadata:
      name: import
    spec:
      containers:
      - name: import
        image: gcr.io/hots-cockroach/website:latest
        command: ["/website", "-importnum", "12280000", "-cockroach=postgres://root@cockroachdb-public:26257/?sslmode=disable"]
      restartPolicy: Never
