apiVersion: batch/v1
kind: Job
metadata:
  name: import
spec:
  template:
    metadata:
      name: import
    spec:
      containers:
      - name: import
        image: gcr.io/hots-cockroach/website:next
        command: ["/website", "-importnum", "6570000", "-cockroach=postgres://root@cockroachdb-public:26257/?sslmode=disable"]
        imagePullPolicy: Always
      restartPolicy: Never
