apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: website
spec:
  selector:
    app: website
    tier: web
  ports:
  - port: 443
    targetPort: 443
    name: website
  - port: 8080
    targetPort: 8080
    name: crdbui
  type: LoadBalancer
  loadBalancerIP: "35.202.222.150"
