apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update
            image: gcr.io/hots-cockroach/website:latest
            command: ["/website", "-updatenew", "csv2.hots.dog"]
          restartPolicy: OnFailure
