apiVersion: batch/v1
kind: Job
metadata:
  name: update
spec:
  template:
    metadata:
      name: update
    spec:
      containers:
      - name: update
        image: gcr.io/hots-cockroach/website:latest
        command: ["/website", "-updatenew", "csv2.hots.dog"]
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 10m
      restartPolicy: OnFailure
