apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: website
    spec:
      initContainers:
      - name: migrate
        image: gcr.io/hots-cockroach/website:latest
        command: ["/website", "-migrate", "-cockroach=postgres://root@cockroachdb-public:26257/?sslmode=disable"]
      containers:
      - name: website
        image: gcr.io/hots-cockroach/website:latest
        env:
          - name: ADDR
            value: ":80" # for https redirection
          - name: AUTOCERT
            value: "hots.dog"
          - name: ACMEDIR
            value: "cloudflare-origin"
          - name: COCKROACH
            value: "postgres://root@cockroachdb-public:26257/?sslmode=disable"
        resources:
          limits:
            cpu: 1m
        ports:
        - containerPort: 443
        - containerPort: 80
        livenessProbe:
          initialDelaySeconds: 3
          httpGet:
            path: /healthz
            port: 443
            scheme: HTTPS
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: website
  ports:
  - port: 443
    targetPort: 443
    name: https
  - port: 80
    targetPort: 80
    name: http
  externalIPs:
    - 10.128.0.5
